### PR TITLE
Continue Development

### LINKED ISSUE #1: Team Management
The platform needs a robust set of user and team management features, including:

### Structure

The 'main' HOLPA interface will have multi-tenancy. Most users will be team members, and the main interface will be at the team level. For users with a single team, all pages are filtered to show only things related to that team. For users with multiple teams, they can switch between teams, but only ever interact with 1 team at a time. 

There is also a 'program' level. A program is made of multiple teams, and intended for situations where there are multiple implementations of HOLPA that all fall under the same program or project. 

For example, the implementation of HOLPA in 8 countries by the core team can be considered 1 program.

A user can be a member of many teams;
A team can be a part of a single 'program'; 
A program is a set of implementations of HOLPA led by a specific organisation/project/program.  The idea is that program leads will have full access to all teams within the program. Team members would still only have access to their own team. 

### Site Admin Panel

- [ ] A User Resource page where admins can:
    - See the full list of registered users, their roles and teams;
    - Send a password reset link to a specific user;
    - Suspend or delete a user;
    - Invite a new user with a specific site-wide role;
    - Invite a new user with to a specific team or program (and with a specific team-wide or program-wide role);
 
- [ ] A Team Resource page where admins can:
    - See the full list of active teams, with space to show the 'status' of the team's progress with the HOLPA implementation. 
    - Create new teams
    - Edit team information
    - Delete teams (?) - need to prevent this when there is actual information / data collected.

- [ ] A Program Resource page where admins can:  
   - See the full list of registered program.
   - Create new programs, and create multiple teams for a program,
   - Edit program information
   - Delete programs (?) - need to prevent this when there is actual information / data collected.

### Program Admin Panel

- [ ] A team and user resource similar to the above.
- [ ] The ability to edit the current program information. 

### Team Panel

- [ ] A user resource similar to the above. 
- [ ] The ability to edit the current team information.

### LINKED ISSUE #2: ODK / XLSForm handling
### Admin Panel

Site admins will be able to fully manage the set of 'xlsform templates' available within the platform. Eventually, they will manage the set of individual modules / sub-modules / indicators. Initially, we will stick to management of complete XLSforms (Household survey + field survey). 

- [x] XLSform Template Resource

- [x] Xlsform Relation manager for teams

### Team Panel

- [x] Xlsform page (similar to TAPE)
- [x] Submission Review page

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to fix #1 and fix #2 

This is not yet ready for review. It is now submitted as progress update.

This branch has merged PR #12 and PR #13 to further develop features required for #1 and #2.

This PR has below changes so far:
1. app panel, add ODK Form Management page
2. admin panel, team resource, add xlsforms relation manager

---

Questions:
 - @dave-mills do we need to have Dataset resource in admin panel?

### CODE REVIEW

**Comment by dave-mills** [comment]
@dan-tang-ssd I would include it for now

**Comment by dan-tang-ssd** [comment]
Hi @dave-mills , here is a progress update, and I need your advice:
- admin panel > Xlsform Templates resource, can create a new xlsform template successfully (I used the simplest_odk_form with one question for testing)
- added Dataset resource in admin panel, created a dataset for main survey, edit existing xlsform template to map Main Survey to main survey dataset
- app panel > ODK Form Management resource. I scanned the QR code to create new project in ODK Collect, created and submitted 1 ODK submission to ODK central
- admin panel > Teams resource > xlsforms relation manager > click "Pull Submissions" button. submissions, entities, entity_values, main_surveys records created, but "No. of Submissions" shows 0 in front end (Any idea...?)

---

Screen shots:

image

image

image

image

image

image

**Comment by dave-mills** [comment]
@dan-tang-ssd - one thought is that if you're not a member of the team, the "0 submissions" might be due to the default global scope on the Submission model. (From memory, it's not overridden even if you have admin access, which is something I think we should change).

**Comment by dan-tang-ssd** [comment]
> @dan-tang-ssd - one thought is that if you're not a member of the team, the "0 submissions" might be due to the default global scope on the Submission model. (From memory, it's not overridden even if you have admin access, which is something I think we should change).

Thank you Dave.

Yes, the default global scope on Submission model is the cause.
We may change it at some point later on.

---

Screen shots:

Login as test admin
image

Login as test user
image

**Comment by dan-tang-ssd** [comment]
I think we reached a point for review now.

Most major features listed in issue #1 and issue #2 are ready. We can work on remaining minor items in forecoming PRs.

We can merge everything into wip branch, then merge wip branch into dev branch and start building a staging site.
The goal is to make it up and running first, so that team members can start working on their own tasks.

I would like to build the staging site then start working on Alex T's ODK form.
As these forms will involve many program changes, e.g. create database tables for main survey, repeat groups, etc,

---

This PR contains below changes:
1. admin panel, team resource, add xlsforms relation manager
2. app panel, add ODK Form Management page, add Show Submissions page
3. app panel > ODK Form Management > Show Submissions > Submissions tab > Edit submission

---

I performed below testing, with positive testing result in local env:
1. Create a new team, crosscheck a new project is created in ODK central
2. Create a new Xlsform Template, set it to Available to use
3. Create Xlsform to a Team, publish xlsform to ODK central, crosscheck a new xlsform is created in ODK central
4. ODK Collect, create a new project by scanning QR code, create and submit a new ODK form
5. Crosscheck ODK submission is received in ODK central
6. Pull submissions into data platform
7. View submission summary, edit submission content

---

Detail steps are listed below for reference:
1. Login as admin, go to admin panel
2. Xlsform Template > create a dataset for Main Survey, create a xlsform template, map main survey section to Main Survey dataset
3. Xlsform Template > set the new xlsform template as "Available for use"
4. Teams > xlsforms relation manager > add XLsform to Team, then Publish it to ODK central
5. Logout, then login as test user, go to app panel automatically
6. ODK Form Management, scan QR code in Android app ODK Collect, create new project, create and submit new ODK form
7. ODK submission has been submitted from ODK Collect to ODK central
8. Logout, login as admin, go to admin panel
9. Teams > xlsforms relation manager > Pull Submissions
10. Logout, login as test user
11. ODK Form Management > Show Submission > Submissions tab, Edit

---

Screen shots:

image

image

**Review by dave-mills — APPROVED** [review]
I agree with your next steps - lets merge this into WIP; merge that into dev and see where we are. Based on this PR, there are still lots of things to do, but we need to see the full picture.

**Pull request merged**
