### PR TITLE
Add Data Export

### LINKED ISSUE #54: Export "processed" data
Includes 
- Data Dictionary;
- Codebook for choice lists;
- 1 worksheet per data level;

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to fix #54 and #80

It is not yet ready for review. It is submitted for progress update.

As discussed with Dave, we will store ODK variables into table columns. 
It is a safer approach because this approach has been used and tested. 

In next phase, we will develop a new approach to store ODK variables into a JSON column called "properties" in main survey table and repeat group tables. 

---

It contains below changes:
 - [x] dashboard, fix namespace for XlsformTemplate class
 - [x] create tables for data dictionary, farm survey data, repeat groups
 - [x] add Model classes for data dictionary, farm survey data, repeat groups
 - [x] add relationships for Model classes
 - [x] create data export classes
 - [x] add route to call data export program, update front end to call data export route
 - [x] use Fieldwork form to submit some testing submissions; retrieve them to check if data stored in tables properly
 - [x] SubmissonController, add custom handling for irrigation data
 - [x] SubmissionController, add custom handling for seasonal_worker_seasons, livestock_uses and fish_uses
 - [x] SubmissonController, add custom handling for products data (pre-defined products and other products)

### CODE REVIEW

**Comment by dave-mills** [comment]
@dan-tang-ssd - thinking about this some more - We wil still need to account for any extra variables that come from the custom indicators, so we'll still have to have 'properties' on each of our main survey data models.

**Comment by dave-mills** [comment]
@dan-tang-ssd - See attached for the list of variables for each dataset. This is the result of me going copying out all the variables in the ODK form and deleting the notes, groups and variables that were only used for the form, (e.g. some calculations to generate labels for enumerator review). 

I've made a few notes too. 

### Data Models

I suggest we keep all the 'survey data' data models in the same namespace / folder: `\App\Models\SurveyData`. Most model names are probably obvious from the datasets, but I suggest `SeasonalWorkerSeason` for "Seasonal Workers in a Season", and similarly `SeasonalLabourerSeason` for "Seasonal Labourers in a Season". 

As per my comment above, all the data models should have a `properties` value that casts to a collection, so that we can account for extra variables that come from custom form sections. The models should also use the trait `HasLinkedDataset`.
[Data Structures.xlsx](https://github.com/user-attachments/files/18099732/Data.Structures.xlsx)

**Review by dave-mills — COMMENTED** [review]
I've merged this namespace bugfix into the dev branch too, as it's useful there asap.

**Comment by dan-tang-ssd** [comment]
@dave-mills - Thanks a lot.

A few little questions before mass production for Model classes:
1. should I create Model classes based on Dataset column in Data Strcuture excel file or Sample submission data export provided by Alex T?
2. should we have one to one mapping for Dataset and Model class?
3. I will revise Dataset seeder files with answers of above question.

---

Screen shots:

Dataset column in Data Structure excel file
image

Sample submission data export provided by Alex T
image

Dataset seeder file
image

**Comment by dave-mills** [comment]
> 1. should I create Model classes based on Dataset column in Data Strcuture excel file or Sample submission data export provided by Alex T?

The export provided by Alex T is the raw submission format. We want to process the data and put it into the format we have defined with the list of datasets. So we want 1 model class for each dataset. 

> 2. should we have one to one mapping for Dataset and Model class?

Yes - 1 data model per dataset entry. On the Dataset model, use the `entity_model` property to link that dataset to a specific model. (e.g. for Products, the `entity_model` might be `\App\Models\SurveyData\Product`).

 - note that there's also a `MorphTo` relationship `model()` on `Dataset`. This is in case the dataset should be linked with a specific model entry, rather than a model class. I mention this as it's not immediately obvious what the difference is and why we have both!

**Comment by dan-tang-ssd** [comment]
@dave-mills - Thank you Dave.

I have another question about Data Structure excel file:
1. For datasets Farms and Locations, can I assume we will need new tables for storing their data? 
(The original farms and locations table are definition data)
In this case, should I add prefix "survey_" to survey data tables? e.g. survey_farms, survey_locations, survey_fishes, survey_fish_uses

**Comment by dave-mills** [comment]
> 1. For datasets Farms and Locations, can I assume we will need new tables for storing their data?
(The original farms and locations table are definition data)
In this case, should I add prefix "survey_" to survey data tables? e.g. survey_farms, survey_locations, survey_fishes, survey_fish_uses

`Farm` and `Location` models are part of the `SampleFrame`. The only time those models should be updated from the submission data is when new entries are added (when the enumerator selects -999 for one of the locations or the farm to enter a new name). So we don't need new models there. 

It looks like you've got the `FarmSurveyData` model set up as the main "farm-level" data model, and have started with the lower level models, linking them up.  I think what you have so far looks good regarding the relationships between `FarmSurveyData` and the other data models like `Fish`. Remember `FIshUse` will have a many-to-one relationship with `Fish`, and `FarmSurveyData` should have a many-to-one relationship with `Farm` (as a single farm may have multiple survey data  entries - either by accident (the enumerator picked the wrong farm), or on purpose (the team are doing a longitudinal study, and are conducting HOLPA on the same farms every few years). 

Does that answer your question?

**Comment by dave-mills** [comment]
Thanks @dan-tang-ssd. 

> In migration files, I tend to use text() instead of string()

Very sensible 👍 

> To complete Data Export this Friday. I will work on data export related programs.
> Then I will need to work on SubmissionController to store testing submission data into various table before I run data export program to verify the result.

Sounds good to me. We already have the setup where if we have linked a form section to a dataset, the ODKLinkService will add an entry to that dataset's `entity_model` when processing (`OdkLinkService` -> `storeMainSurveyToCustomTable` and `storeRepeatGroupToCustomTable`), so the custom processing in the SubmissionController might be just for a few little parts (I can't think of anything, but I'm sure there'll be a few bits).

**Comment by dan-tang-ssd** [comment]
I tried to create xlsform template for Fieldwork form for tesitng.

I download the latest Fieldwork form from below link:
 - Fieldwork - https://docs.google.com/spreadsheets/d/1Xzbemo-lDCZTz6C2Ig5S2_0rcFOynwwpY_AX09fs1bI/edit?usp=sharing

When I create xlsform template, it complains for missing list name "sub_district" in choices sheet.
I added "sub_district" in choices sheet manually, tried again. Then I got similar error but it is for list name "farm" now.

I will use the previous version of Fieldwork form dated on 2024-12-03 for testing first.

---

Screen shots:

image

image

**Comment by dave-mills** [comment]
@dan-tang-ssd  - as the locations section is identical in each form, the simple fix is to copy over the choices lists from the household form. I've now done that on the Google Sheet: 

CleanShot 2024-12-13 at 11 58 54

**Comment by dan-tang-ssd** [comment]
@dave-mills - Thanks a lot.

I downloaded the latest Fieldwork form from Google Sheet.
I can create xlsform template successfully.

When I create xlsform, it throws error...
The xlsform is created, but there is no "Publish" button.

In app panel, I got another error when I access "ODK Form Management"...

---

Screen shots:

Error occurred when creating xlsform...
image

Xlsform is created but there is no "Publish" button
image

app panel > ODK Form Management
image

Error occurred
image

**Comment by dan-tang-ssd** [comment]
@dave-mills - I did below to get latest code from dev branch as discussed.

 - git checkout dev
 - git pull
 - git checkout add-data-export
 - git pull

---

I also did below:

 - git submodule update
 - stop queue
 - clear queue
 - start queue
 - download latest Fieldwork form from Google Sheet

I got error when I create a xlsform template.
Laravel queue throws error and stopped running.

---

Screen shots:

image

image

**Comment by dan-tang-ssd** [comment]
I added value to column datasets.entity_model, so that each dataset links to a Model class, which links to a database table.

When I retrieve Fieldwork form submission, farm_survey_data and fieldwork_sites records created.

When I retrieve Household form submission, only farm_survey_data record created.

I added some debug message and check against xlsform_template_sections records and submission JSON content.
It is strange that the paths for repeat groups do not match with JSON data of Household form.

E.g. In xlsform_template_sections, the path for "other_products" is "/survey/farm_characteristics/other_products/other_product_pos".

But in JSON data, farm_characteristics in under /survey/income, not /survey.

Questions:
1. Is there anything change since last Friday...? 
e.g. Household form, xlsform_template_sections records, submission data, etc...

---

Screen shots:

Fieldwork form JSON data
image

Household form JSON data
image

xlsform_template_sections records
image

datasets records
image

**Comment by dave-mills** [comment]
@dan-tang-ssd I wonder if it's a difference between how xlsform versions have been created.

> Is there anything change since last Friday...?
> e.g. Household form, xlsform_template_sections records, submission data, etc...

On ODK Central - you'll see different versions of the form uploaded over the course of the weekend: https://odk-test.stats4sdtest.online/#/projects/1282/forms/holpa-household-fri13-5/versions

These were from tests of importing + generating the Xlsform file. I'll take a look to see if there are substantive changes (if there are, that's an issue!)

**Comment by dave-mills** [comment]
@dan-tang-ssd - ahhah, yes - the Friday version has an issue where the "income" group was not closed at the right time; no idea if that was a bug in the form template or in how the xlsform was generated. (Probably how the xlsform file was generated, as the xlsform_template_sections suggest it is correct in the template file). 

Either way - that is the reason all those groups are sub-groups of "income" in that submission. In the current version, there should only be 2 sub-groups of income: 

CleanShot 2024-12-16 at 15 08 36

I suggest trying with a new submission, if you have not already done so, and probably deleting that old submission from the ODK Central server as it looks to be in the wrong format.

**Comment by dan-tang-ssd** [comment]
Thank you Dave.

I submitted a Household form via Enketo. When I retrieve submissions, no submissions can be retrieved.
It seems that the corresponding xlsform version is not existed in my local db. Would you provide the latest xlsform_versions?

---

$xlsformVersion = $xlsform->xlsformVersions()->firstWhere('version', $entry['__system']['formVersion']);

This statement returns null

---

Screen shots:

xlsform_versions records in my local db
image

**Comment by dave-mills** [comment]
Hi Dan,

I cannot give you my entries because I have since reset the database working on other things. But, we can figure out exactly what they should be, because the version and odk_version should equal the $entry['__system']['formVersion']. Looking at the data from ODK Central, that should equal "2024-12-15  12:39:25", but you can confirm because you're pulling the data.

The schema for the version is not used (I have just checked the processing code to figure that out), so that can equal anything.

Dave



--
Dave Mills (he / him)

Data Engineer
Statistics for Sustainable Development
www.stats4sd.org<http://www.stats4sd.org/> | ***@***.******@***.***>

Statistics for Sustainable Development is a social enterprise.
Registered in England and Wales as a Company Limited by Guarantee No. 10168747

Emails often dictated - apologies for any formatting or spelling errors.
On 16 Dec 2024 at 18:17 +0000, dan-tang-ssd ***@***.***>, wrote:

Thank you Dave.

I submitted a Household form via Enketo. When I retrieve submissions, no submissions can be retrieved.
It seems that the corresponding xlsform version is not existed in my local db. Would you provide the latest xlsform_versions?

________________________________

$xlsformVersion = $xlsform->xlsformVersions()->firstWhere('version', $entry['__system']['formVersion']);

This statement returns null

________________________________

Screen shots:

xlsform_versions records in my local db
image.png (view on web)<https://github.com/user-attachments/assets/0d6d2acf-0888-4b73-82d5-165db66bd833>

**Comment by dave-mills** [comment]
And for the fieldwork survey, the version and odk_version will be: "2024-12-15 12:39:25", as shown here: 

CleanShot 2024-12-16 at 20 13 16

**Comment by dan-tang-ssd** [comment]
Thank you Dave.

I have updated xlsform_versions.version and xlsform_versions.odk_version to "2024-12-15 12:39:25".

There are 3 household form submissions in ODK central now.
1. First submission with first version. submitted on 2024-12-13 16:08. It will not be retrieved to application now.
2. Second submission which is submitted by Alex T on 2024-12-16 17:21:19.
3. Third submission which is submitted by Dan on 2024-12-16 17:43:38.

Application can retrieve second and third submissions now. But no records created for repeat groups.
I did a checking on submission JSON content, those repeat groups arrays are still inside "income"...

Um... Is the "income bug" fixed ODK form submitted to ODK central yet?

---

Screen shots:

xlsform_versions
image

xlsform_template_sections
image

second submission
image

third submission
image

**Comment by dan-tang-ssd** [comment]
@dave-mills - Here is a progress update for retrieving submissions.

Fieldwork form submissions, records created for below tables:
1. farm_survey_data
2. fieldwork_sites

---

Household form submissions, records created for below tables:
1. farm_survey_data
2. products
3. permanent_workers
4. ecological_practices
5. livestocks
6. fishes

No record created for below tables:
1. seasonal_worker_seasons
2. livestock_uses
3. fish_uses
4. growing_seasons (customised handling in SubmissionController)

---

Questions:
For Crops dataset record, entity_model is App\Models\LookupTables\Crop instead of App\Models\SurveyData\Crop. 
App\Models\LookupTables\Crop model's table is "crop_list_entries". 
1. crops
2. crop_list_entrties

**Comment by dan-tang-ssd** [comment]
Here is a data export excel file for quick reference.
[HOLPA-data-export.zip](https://github.com/user-attachments/files/18167478/HOLPA-data-export.zip)

**Comment by dave-mills** [comment]
Thanks for the update.

To your points and questions :

- The "App\Models\LookupTables\Crop" should not exist; it is not used and can ignored or removed. (Those LookupTables classes came originally from copying over our example code for lookup tables. I've since refined that so that we can get the lookup lists directly from ChoiceListEntry entries. The LookupTables\Crop model is gone in my current branch). 
-
- Remind me - what is the growing_seasons dataset? I don't see it in the Data Structures Excel I shared. The only thing I can think of is it being the data about irrigation % each season, which should not be a separate dataset (we discussed that it needs to be flattened and we put 12 variables into the main Farm Survey Data - e.g. irrigation_percentage_jan, irrigation_percentage_feb, etc.).

I assume seasonal_worker_seasons, livestock_uses and fish_uses are not populated because the core ODK Submission handling doesn't support nested repeats, so we'll need to manually handle those repeat sections for now.

**Comment by dan-tang-ssd** [comment]
@dave-mills - Thanks a lot for your reply.

> Thanks for the update.
> 
> To your points and questions :
> 
>     * The "App\Models\LookupTables\Crop" should not exist; it is not used and can ignored or removed. (Those LookupTables classes came originally from copying over our example code for lookup tables. I've since refined that so that we can get the lookup lists directly from ChoiceListEntry entries. The LookupTables\Crop model is gone in my current branch).

I have updated datasets.entity_model and it can create crops records now.


> 
>     * Remind me - what is the growing_seasons dataset? I don't see it in the Data Structures Excel I shared. The only thing I can think of is it being the data about irrigation % each season, which should not be a separate dataset (we discussed that it needs to be flattened and we put 12 variables into the main Farm Survey Data - e.g. irrigation_percentage_jan, irrigation_percentage_feb, etc.).

Um... one submission can contain mutliple "irrigation_months" and "irrigation_percentage". Should we store them in a separate tables "irrigations"?

> I assume seasonal_worker_seasons, livestock_uses and fish_uses are not populated because the core ODK Submission handling doesn't support nested repeats, so we'll need to manually handle those repeat sections for now.

---

Screen shots:

image

**Comment by dave-mills** [comment]
>Um... one submission can contain mutliple "irrigation_months" and "irrigation_percentage". Should we store them in a separate tables "irrigations"?

I have argued 'no' to that question in previous comments and described my idea in the Data Structures Excel file, and I stand by that for now.

The question asks you to define your seasons by selecting months, then for each season, what is the % of land irrigated. While there is no logical check preventing users from selecting one month in multiple seasons, that would be a surprising result! So I hope/assume that we will get something like in your screenshot, where we can split it out into 12 separate variables. In the case you screenshotted, I think we could have: 

`irrigation_percentage_month_1` = 0
`irrigation_percentage_month_2` = 0
`irrigation_percentage_month_3` = 50
`irrigation_percentage_month_4` = 50
`irrigation_percentage_month_5` = 50
`irrigation_percentage_month_6` = 50
`irrigation_percentage_month_7` = 50
`irrigation_percentage_month_9` = 25
`irrigation_percentage_month_10` = 25
`irrigation_percentage_month_11` = 25
`irrigation_percentage_month_12` = 25

I would argue for splitting it into a separate table *if* the 'seasonality' of it is important - e.g. if these irrigation seasons were the same set of seasons as the seasons for seasonal workers and other questions. But given that doesn't seem to be necessarily true, I don't think adding a separate data level just for this single question (as it is basically a single question "what % do you irrigate in a given time period") is worth it. 

In rare cases where  someone puts the same month in multiple seasons, I would select the higher value, e.g.: if a submission had this: 
CleanShot 2024-12-17 at 17 54 51

... I would give month 9 the '50%' irrigation. This is probably a case where it'd be better for someone in the team to review the raw data and make a decision, and maybe if we add auto validation checks in future we could highlight this type of case.

**Comment by dan-tang-ssd** [comment]
Progress update:

1. SubmissionController, added custom handling for irrigation data to 12 columns in farm_survey_data table.
2. Added a command program to create fish_uses from nested repeat group in submission content. Hopefully livestock_uses and seasonal_worker_seasons should be similar.

**Comment by dan-tang-ssd** [comment]
I think it is ready for review.

I will add static content and dynamic content for Data Dictionary in another PR.

---

But one thing need to take a look...

When retrieving Fieldwork form:
 - 6 submissions retrieved
 - number of submissions updated in front end
 - notification showed

when retrieving Household form:
 - Error 500 occurred
 - It retrieved 5 submissions, but the number of submission not updated in front end
 - there is no notification showed (likely due to Error 500 occurred)

If I dump a message in OdkLinkService, error 500 not showed, but the little icon next to "Manually Get Submissions" keeps loading...

Similar issue happened in other applications before, any idea on how to get it fixed?

---

Screen shots:

When retrieving Fieldwork form
image

When retrieving Household form
image

image

**Comment by dave-mills** [comment]
> If I dump a message in OdkLinkService, error 500 not showed, but the little icon next to "Manually Get Submissions" keeps loading...

I loaded up this branch and reset my database to the state I shared with you that includes these test forms. I also got that 500 error, but I got it right away, not after the 5th submission. 

Looking through the getSubmissions(), I assume it's stopping at the abort(500). To test this idea, I added a ray statement just before that. That told me the error was at that point as I didn't have the xlsform_versions in the database. I assume that you got the first 5 submissions because you'd manually added the versions into the database that matched those subs, but perhaps the newest submission used a version you didn't have?

After manually adding in an xlsform_version entry for each version on the form (https://odk-test.stats4sdtest.online/#/projects/1282/forms/holpa-household-fri13-5/versions), it now works to get all 6 submissions.  

CleanShot 2024-12-18 at 12 21 27


For reference, my versions table looks like this: (schema entries are un-important as they're not currently used anywhere)
CleanShot 2024-12-18 at 12 15 05

**Review by dave-mills — COMMENTED** [review]
Looks great - I've just merged the NaN fix you made in the package into the main 'holpa' package branch, so that should be fine when merging. I'll take a quick look at the other merge conflicts now

**Comment by dan-tang-ssd** [comment]
@dave-mills - I have added custom handling to populate products data (for both pre-defined products and other products).

It works fine. I think it is now ready for review.

**Pull request merged**
