### PR TITLE
Odk Builder - revised xlsform template imports

### PR DESCRIPTION
**Pull request by dave-mills**
WIP towards the building of customised ODK forms. This PR is submitted to bring in the revised Xlsformtemplate importers that work on the default queue instead of in sync. This avoids the timeout errors seen with the larger Household survey.

### CODE REVIEW

**Comment by dave-mills** [comment]
### Implementation Notes
All the new Export classes, plus the addition to the TeamResource and XlsformsRelationManager are currently placeholders. 

For the imports, I have made sure all the Import classes implement `ShouldQueue`, so they should all be run on the default job queue, and not on the same process that does all the ODK Link Package processing. 

The big structural change is that now, instead of one big Import class that handles creating + deleting `SurveyRow`, `ChoiceList`, `ChoiceListEntry` and `LanguageString` models, we have different import classes doing different things. More of the logic of what to import when is brought into the `HandleXlsformTemplateAdded` listener, and that class goes through the following: 

1. Gets the list of `$translatableHeadings` from the file (columns that should be imported as LanguageString entries), using the `XlsformTemplateHeadingRowImport` class.
2. Imports `ChoiceList` entries using `XlsformTemplateChoiceListImport`
3. Imports the `SurveyRow` and `ChoiceListEntry` entries using the "main" `XlsformTemplateWorkbookImport` class.
4. Loops through all the `$translatableHeadings` and imports the `LanguageString` entries with `XlsformTemplateLanguageStringImport`. 
  - Note  that there is 1 import queued _per $translatableHeading_. That way, we can keep using toModel (which requires 1 model is created per $row), and take advantage of using `WithChunkReading` (which is required for ShouldQueue).

**Comment by dave-mills** [comment]
@dan-tang-ssd - Given this is kind of a partial PR, I don't think there's a need to go in detail through the whole thing. Can you confirm if you can successfully add the HOLPA household + fieldwork surveys as templates, and that: 

- It is pushed to ODK Central ok
- The jobs on the queue run fine. 

There are some tests for the imports in `tests\Feature\XlsformTemplateImportTest` that test that the survey rows, choice lists, choice list entries, xlsform template lanaguages and language strings are all imported (and updated/deleted) on import. (`php artisan test` - should be 6 passing tests in the whole suite)

**Comment by dan-tang-ssd** [comment]
I did below to update my local env:

==========

git checkout dev

git pull

git checkout odk-builder

git pull

composer install

npm install

php artisan migrate:fresh --seed

==========

I start a queue by below command:

php artisan queue:work

==========

I can create Fieldwork form successfully, but I cannot create Household form due to 30 seconds timeout.

I have updated timeout duration from 60 seconds to 3600 seconds in my php.ini.
It looks like there is another timeout config item somewhere else, maybe Laravel Herd. I did a checking in Laravel Herd user interface but I cannot find timeout related configuration.

==========

There are some errors in laravel log file:

[2024-12-09 15:27:13] local.INFO: MediaHasBeenAdded event fired!  

[2024-12-09 15:27:33] local.ERROR: Attempt to read property "id" on null {"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at C:\\public\\holpa-platform\\app\\Imports\\XlsformTemplate\\XlsformTemplateLanguageStringImport.php:104)
[stacktrace]
#0 C:\\public\\holpa-platform\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(281): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Attempt to read...', 'C:\\\\public\\\\holpa...', 104)

[2024-12-09 15:27:57] local.ERROR: Maximum execution time of 30 seconds exceeded {"userId":2,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at C:\\public\\holpa-platform\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:693)
[stacktrace]
#0 {main}
"} 

[2024-12-09 15:28:02] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'xlsform_template_id' in 'where clause' (Connection: mysql, SQL: update `choice_list_entries` set `updated_during_import` = 0, `choice_list_entries`.`updated_at` = 2024-12-09 15:28:02 where `xlsform_template_id` = 3) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'xlsform_template_id' in 'where clause' (Connection: mysql, SQL: update `choice_list_entries` set `updated_during_import` = 0, `choice_list_entries`.`updated_at` = 2024-12-09 15:28:02 where `xlsform_template_id` = 3) at C:\\public\\holpa-platform\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:825)
[stacktrace]

[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'xlsform_template_id' in 'where clause' at C:\\public\\holpa-platform\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:592)
[stacktrace]
#0 C:\\public\\holpa-platform\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(592): PDO->prepare('update `choice_...')

**Comment by dave-mills** [comment]
@dan-tang-ssd I've made a few minor changes - one of which should fix the errors you saw in the logs about xlsform_template_id on choice_list_entries. 

The main issue I fixed was the ordering of queued jobs. Previously the LanguageString imports were starting before the main XlsformTemplateWorkbook import was complete, which meant it was trying to link LanguageString entries to ChoiceListEntries that did not yet exist. I've fixed this using careful job chaining in the latest commit.

**Comment by dan-tang-ssd** [comment]
Thank you Dave. 
I have pulled latest code for testing.

After updating config item "max_execution_time" from 30 to 3600, I still got the same error. 
I will reboot and try again to see if it works.

**Comment by dave-mills** [comment]
> After updating config item "max_execution_time" from 30 to 3600, I still got the same error.
> I will reboot and try again to see if it works.

No need to reboot; but you will need to restart PHP for the updated ini to take effect...

**Comment by dan-tang-ssd** [comment]
I can create xlsform template for both fieldwork form and household form now.

I can create xlsform for fieldwork.
When I create xlsform for household form, memory error occurred...
Um.... do we need a large portion of memory for this task...?

By the way, I would consider this PR has resolved the timeout issue when creating xlsform.
We can merge this PR into dev branch, then create xlsform for household form for testing in staging env.

---

Screen shots:

image

**Review by dan-tang-ssd — APPROVED** [review]

**Comment by dave-mills** [comment]
@dan-tang-ssd  - thanks. It's interesting seeing the issues that are appearing with testing on a much larger form than our usual ones. I agree that the memory issue isn't a blocker for this PR, especially as the deployment of Xlsforms will be quite different to what it is now (we will be generating the xlsform file from the database, instead of using the uploaded one).

**Pull request merged**
