### PR TITLE
Xlsform Templates Resource, View Page, Minor Refinements

### LINKED ISSUE #48: ODK form template availability - make it easier to see/update
On ODK Template view page:
- make top section non collapsible;
- add colour to icon for "Available to Platform users?" entry (yes = green; no = grey);

- Add action (in section or in page header?) to mark template as available.

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to fix #48 

It is now ready for review.

It contains below changes:
 - make top section non collapsible
 - add colour to icon for "Available to Platform users?" entry (yes = green; no = grey)
 - Add action (in section or in page header?) to mark template as available

---

Questions:
1. I think a "Make Template Available" button is good enough to provide a convenient and obvious way to make a template available. Probably we do not need to provide a convenient way to make a template unavailable. Um... How likley we need to make a template unavailable...?

### CODE REVIEW

**Review by dave-mills — COMMENTED** [review]
This works fine, but you made these changes in the odk-link package, rather than only working in the holpa platform repo as I had asked. 

In the odk-link package, your new branch was taken from the 5-month-old commit that was being used in Holpa, and now that branch cannot be easily merged into the dev branch because it doesn't include the latest dev changes. This will be a bit complicated, which is why I had said we should work in the single repo to get things done more quickly. 

That said, now this is in the odk-link package, it doesn't make sense to move it out, only to move it back in next month. I will reconcile your branch with the dev branch and fix the dev branch so it works on HOLPA, then pass it back to you to review.

**Comment by dave-mills** [comment]
@dan-tang-ssd  - I have done the following in the filament-odk-link package: 

1. merged your package PR (https://github.com/stats4sd/filament-odk-link/pull/44) into dev;
2. fixed the namespacing and class issues on a new branch and sent you a PR: https://github.com/stats4sd/filament-odk-link/pull/45
3. Switched to using that PR branch here. 

This refine-xlsform-template branch should now be working, _and_ be on the latest version of the odk-link package. Can you check it loads ok? if it's good, then we can merge the package PR back to dev, update this branch to reference dev in the package, then merge this branch in 👍 .

**Comment by dan-tang-ssd** [comment]
@dave-mills - Thanks a lot.

Here is what I did, I think it is good to merge.

==========

main repo

git checkout dev

git pull

git checkout refine-xlsform-template-view-page

git pull

==========

submodule

git checkout dev

git pull

git checkout namespace-fixing

git pull

==========

perform testing, check if 3 changes in this PR remains unchange, success

---

Screen shots:

image

image

---

Questions:
1. In Xlsform Templates resource, list view, previously it shows all xlsform_templates record (with error 504 Gateway timeout). But now it only shows xlsform_templates that created successfully during creation process. Is this the expected behaviour?

Screen shots:

image

image

**Comment by dave-mills** [comment]
> In Xlsform Templates resource, list view, previously it shows all xlsform_templates record (with error 504 Gateway timeout). But now it only shows xlsform_templates that created successfully during creation process. Is this the expected behaviour?

Yes. The view now shows only xlsformtemplates owned by the 'platform', to have the opportunity for individual programs/teams/users to also own xlsformtemplates. This has the added feature of only showing templates that were successfully processed during creation.

**Pull request merged**
